name: Vulnerability Scanning CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Vulnerability Scanning
      uses: geekNero/vulnerability-scanning@development
